version: "3.1"

services:
  nginx:
    build: docker/nginx
    container_name: PROJECT_CRUD_NGINX_YII
    restart: always
    volumes:
      - ${APPLICATION_DIR}:/var/www/app
      - ./docker/nginx/config/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 127.0.0.1:${NGINX_PORT}
    networks:
      - project_crud_mvc_yii

  php:
    build: docker/php
    restart: always
    container_name: PROJECT_CRUD_PHP_YII
    volumes:
      - ${APPLICATION_DIR}:/var/www/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - project_crud_mvc_yii

  postgres:
    image: postgres:12.1
    restart: always
    container_name: PROJECT_CRUD_POSTGRES_YII
    volumes:
      - ${PGSQL_ROOT}:/var/lib/postgres/data/pgdata
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
    ports:
      - ${PGSQL_PORT}
    networks:
      - project_crud_mvc_yii

networks:
  project_crud_mvc_yii:
    driver: bridge